blank_issues_enabled: false
contact_links:
  - name: Questions
    url: "https://github.com/Novik/ruTorrent/discussions/categories/q-a"
    about: "Please ask questions related to ruTorrent in the Discussions section"
